# Paths
raw_data_path: './data/raw/'
meta_data_path: './data/raw/meta_data.csv'
processed_data_path: './data/processed/'

# Pytorch
epochs: 50
# Game data
games: ['ms_pacman']

# Dataset parameters
batch_size: 32
num_workers: 3
shuffle: False

# Data pre-processing
original_size: [210, 160]
size_x: 84
size_y: 84
train_sub: ['R']
test_sub: ['K']
grey_scale: True
stack_length: 3
sigma: 5
use_fixation: True
maxdist: 25
sampling_rate: 1000

# Data writer parameters
data_writer:
  shard_write: False
  shard_maxcount: 6250
  data_write_freq: 3
